<a href="https://colab.research.google.com/github/realvoice98/bigdata-use-of-python/blob/main/0522%EB%8F%85%ED%95%99%2C_tensor_flow_%EC%A0%81%EC%9D%91%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [4]:
텐서 = tf.constant([3,4,5])
텐서2 = tf.constant([6,7,8])

In [5]:
print(텐서+텐서2)

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [16]:
# tf.add(),tf.subtract(),tf.devide(),tf.multiply()
print(tf.add(텐서,텐서2))
print(tf.subtract(텐서,텐서2))
print(tf.divide(텐서,텐서2))
print(tf.multiply(텐서,텐서2))


tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([0.5        0.57142857 0.625     ], shape=(3,), dtype=float64)
tf.Tensor([18 28 40], shape=(3,), dtype=int32)


# 실전예제 - 데이터를 가지고 대학교 합격률을 맞추자

텐서플로우를 활용하여 모델생성

In [19]:
import tensorflow as tf
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(64,activation='tanh'),
  tf.keras.layers.Dense(128,activation='relu'),
  tf.keras.layers.Dense(1,activation='sigmoid')
]) # 모델 생성 _ Sequnetial 함수를 사용하면, 신경망 레이어들을 쉽게 만들어줌


In [49]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics='accuracy')

In [63]:
model.fit(np.array(x데이터),np.array(y데이터),epochs=100)

Epoch 1/100
14/14 [==============================] - 0s 3ms/step - loss: 0.5340 - accuracy: 0.7341
Epoch 2/100
14/14 [==============================] - 0s 3ms/step - loss: 0.5302 - accuracy: 0.7435
Epoch 3/100
14/14 [==============================] - 0s 5ms/step - loss: 0.5649 - accuracy: 0.7059
Epoch 4/100
14/14 [==============================] - 0s 4ms/step - loss: 0.5117 - accuracy: 0.7600
Epoch 5/100
14/14 [==============================] - 0s 3ms/step - loss: 0.5247 - accuracy: 0.7365
Epoch 6/100
14/14 [==============================] - 0s 3ms/step - loss: 0.5501 - accuracy: 0.7271
Epoch 7/100
14/14 [==============================] - 0s 3ms/step - loss: 0.5130 - accuracy: 0.7435
Epoch 8/100
14/14 [==============================] - 0s 3ms/step - loss: 0.5125 - accuracy: 0.7671
Epoch 9/100
14/14 [==============================] - 0s 3ms/step - loss: 0.5083 - accuracy: 0.7647
Epoch 10/100
14/14 [==============================] - 0s 3ms/step - loss: 0.5154 - accuracy: 0.7576
Epoch 11/

In [105]:
print(np.array(x데이터).shape)
print(np.array(y데이터).shape)

(425, 3)
(425,)


In [151]:
예측값 = model.predict([[720,3.67,2],[410,5.1,1]])
print(예측값)

ValueError: ignored

판다스를 이용하여 데이터 가져오기

In [22]:
import pandas as pd
data = pd.read_csv('/content/gpascore.csv')
print(data)

     admit    gre   gpa  rank
0        0  380.0  3.21     3
1        1  660.0  3.67     3
2        1  800.0  4.00     1
3        1  640.0  3.19     4
4        0  520.0  2.33     4
..     ...    ...   ...   ...
421      1  750.0  3.44     4
422      1  710.0  3.66     4
423      0  450.0  3.25     4
424      1  760.0  3.76     2
425      1  710.0  3.82     3

[426 rows x 4 columns]


In [31]:
data.isnull().sum() # gre행이 비어있다.
data = data.dropna() #빈칸의 행을 지워준다.
#data.fillna(100) #빈칸에 값을 넣어줌 100
data.isnull().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [32]:
print(data['gpa'])

0      3.21
1      3.67
2      4.00
3      3.19
4      2.33
       ... 
421    3.44
422    3.66
423    3.25
424    3.76
425    3.82
Name: gpa, Length: 425, dtype: float64


In [35]:
y데이터 = data['admit'].values # admit행의 모든값을 리스트형태로 저장
print(y데이터)

[0 1 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 1 1 1 1 0 1 0 0 1 0 0 0 0
 1 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 1 0 0 0 0 1
 1 0 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0
 0 0 1 1 1 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1 0 0 1
 0 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 1 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1 1 1 0 1
 0 0 0 0 1 0 0 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1
 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 0
 0 0 1 1 1 0 0 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 1 0 1 1 1 0 1 0 0 1 0 0 0
 0 0 0 0 1 1 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0
 1 1 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1 1 1 1 0 0 1 0 0 1 1 1 1
 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 1 0 0 1 1 0 0 1
 0 0 1 1 0 1 0 1 0 1 0 0 1 1 1 0 1 1]


In [39]:
x데이터 = []
for i,rows in data.iterrows():
  x데이터.append([rows['gre'],rows['gpa'],rows['rank']]) #x데이터에 필요한 데이터 넣기


In [40]:
print(x데이터) # 데이터가 다 들어간것을 확인할 수 있음.

[[380.0, 3.21, 3.0], [660.0, 3.67, 3.0], [800.0, 4.0, 1.0], [640.0, 3.19, 4.0], [520.0, 2.33, 4.0], [760.0, 3.0, 2.0], [560.0, 2.98, 1.0], [400.0, 3.08, 2.0], [540.0, 3.39, 3.0], [700.0, 3.92, 2.0], [750.0, 3.6, 4.0], [440.0, 3.22, 1.0], [760.0, 4.0, 1.0], [600.0, 3.08, 2.0], [700.0, 4.0, 1.0], [480.0, 3.44, 3.0], [490.0, 3.87, 4.0], [360.0, 2.56, 3.0], [800.0, 3.75, 2.0], [500.0, 3.17, 3.0], [660.0, 3.63, 2.0], [600.0, 2.82, 4.0], [680.0, 3.19, 4.0], [760.0, 3.35, 2.0], [800.0, 3.66, 1.0], [620.0, 3.61, 1.0], [520.0, 3.74, 4.0], [780.0, 3.22, 2.0], [520.0, 3.29, 1.0], [540.0, 3.78, 4.0], [760.0, 3.35, 3.0], [600.0, 3.4, 3.0], [800.0, 4.0, 3.0], [360.0, 3.14, 1.0], [400.0, 3.05, 2.0], [580.0, 3.25, 1.0], [520.0, 2.9, 3.0], [500.0, 3.13, 2.0], [520.0, 2.68, 3.0], [560.0, 2.42, 2.0], [580.0, 3.32, 2.0], [600.0, 3.15, 2.0], [500.0, 3.31, 3.0], [700.0, 2.94, 2.0], [460.0, 3.45, 3.0], [580.0, 3.46, 2.0], [500.0, 2.97, 4.0], [440.0, 2.48, 4.0], [400.0, 3.35, 3.0], [640.0, 3.86, 3.0], [440.0,

데이터 형변환 numpy

In [44]:
import numpy as np # 데이터를 학습시키기위해 넘파이형으로 변경해야함.
np.array(x데이터)
np.array(y데이터)

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,

메모.
모델을 향상
+ 데이터 전처리 과정
+ 모델 튜닝, 레이어를 추가해보거나 유닛수를 줄여보거나 활성함수를 수정해보는것

전체적으로 다시 복습해보자면
1. 데이터를 가져와서 그것을 판다스를 이용해 가공한다.
2. 모델을 만든다.
3. 가공된 데이터를 가지고 , 컴파일하고->학습하고->예측 까지 진행.
4. 예측률을 높이기 위해 데이터 전처리 & 모델튜닝을 진행하여 높힌다.

# 혼자 다른 데이터로 복습해보기.

이번에는 데이터 가공먼저 해볼것이야.

In [110]:
import pandas as pd # 데이터를 가져오기위한 패키지
import numpy as np # 가져온 데이터를 딥러닝 모델에 넣기위한 모델
data = pd.read_csv('/content/Fish1.csv')
print(data)

     Species  Weight  Length1  Length2  Length3   Height   Width
0        0.0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0.0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0.0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0.0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0.0   430.0     26.5     29.0     34.0  12.4440  5.1340
..       ...     ...      ...      ...      ...      ...     ...
154      NaN    12.2     11.5     12.2     13.4   2.0904  1.3936
155      NaN    13.4     11.7     12.4     13.5   2.4300  1.2690
156      NaN    12.2     12.1     13.0     13.8   2.2770  1.2558
157      NaN    19.7     13.2     14.3     15.2   2.8728  2.0672
158      NaN    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]


In [135]:
data.isnull().sum() # 전처리할 데이터 1로 모두 수정
ydata = data.fillna(1)
ydata = ydata['Species'].values #.values #Species 안에 Bream만 뽑고 싶은데 모르겠다 ㅠ,,ㅠ _y데이터 확보 완료
print(ydata) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [113]:
xdata=[]
for i,rows in data.iterrows():
  xdata.append([rows['Weight'],rows['Length1'],rows['Height'],rows['Width']]) #x데이터 확보 완료

In [133]:
print(ydata)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
154    1.0
155    1.0
156    1.0
157    1.0
158    1.0
Name: Species, Length: 159, dtype: float64


모델을 생성해보자 !

In [146]:
import tensorflow as tf

models = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(64,activation='tanh'),
    tf.keras.layers.Dense(1,activation='sigmoid')                        
])
# 레이어가 3개인 모델 생성

In [147]:
models.compile(optimizer='adam',loss='binary_crossentropy',metrics='accuracy')

In [148]:
models.fit(np.array(xdata),np.array(ydata),epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 0.7419 - accuracy: 0.5094
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6852 - accuracy: 0.4969
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6491 - accuracy: 0.5786
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6429 - accuracy: 0.5723
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6271 - accuracy: 0.6101
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6286 - accuracy: 0.6038
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6467 - accuracy: 0.5975
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6403 - accuracy: 0.6038
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6489 - accuracy: 0.5975
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.6470 - accuracy: 0.5975
Epoch 11/100
5/5 [===========

In [145]:
# 오류 - `logits` and `labels` must have the same shape, received ((None, 64) vs (None, 1)) 해결해보기
print(np.array(xdata).shape)
print(np.array(ydata).shape)
# 모델 생성할때 마지막 sigmoid라인을 64 노드 생성으로 했어 ㅡㅡ 아 ..

(159, 4)
(159,)


In [149]:
print(data)

     Species  Weight  Length1  Length2  Length3   Height   Width
0        0.0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0.0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0.0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0.0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0.0   430.0     26.5     29.0     34.0  12.4440  5.1340
..       ...     ...      ...      ...      ...      ...     ...
154      NaN    12.2     11.5     12.2     13.4   2.0904  1.3936
155      NaN    13.4     11.7     12.4     13.5   2.4300  1.2690
156      NaN    12.2     12.1     13.0     13.8   2.2770  1.2558
157      NaN    19.7     13.2     14.3     15.2   2.8728  2.0672
158      NaN    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]


In [153]:
#xdata.append([rows['Weight'],rows['Length1'],rows['Height'],rows['Width']])
예측값 = models.predict([[248,32,13,5],[290,41,23,9]])
print(예측값)



[[0.45426205]
 [0.41991657]]
